<?php

namespace AuditionBundle\Repository;

/**
 * AuditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditionRepository extends \Doctrine\ORM\EntityRepository
{
}
